# Generated by Django 5.2 on 2026-04-18 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianteproducto',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.varianteproducto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.varianteproducto'),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'talla', 'color'), name='unique_producto_variante'),
        ),
    ]
